Upload photo
space928/WAD2-Flinder pull request #16
Opened 2022-03-25 21:18 UTC by desolee

2022-03-25 21:21 UTC, desolee commented on flinder/flinderserver/views.py
> +        imgfiles = request.FILES.get('img')
I can't receive img, 
![image](https://user-images.githubusercontent.com/99375266/160202365-cacc4811-00f3-4ff6-918f-5d21c6ee3986.png)

2022-03-25 21:31 UTC, space928 requested changes

2022-03-25 21:31 UTC, space928 commented on flinder/flinderserver/urls.py
> +    path('upload_photos', csrf_exempt(views.upload_photos), name="upload_photos"),
Why is this csrf exempt?

2022-03-25 21:31 UTC, space928 commented on flinder/flinderserver/views.py
> +        img = Pictures(picture=imgfile, description=imgfile.name)
typo in imgfile should be imgfiles

2022-03-25 21:31 UTC, space928 commented on flinder/templates/flinder/upload_photos.html
> +            </form>
I'm currently working on updating the HTML template, so I'll reject your changes on the html.

2022-03-25 21:49 UTC, desolee commented on flinder/flinderserver/views.py
> +        img = Pictures(picture=imgfile, description=imgfile.name)
Oh, thank you I didn't notice that

2022-03-25 22:23 UTC, desolee commented on flinder/flinderserver/urls.py
> +    path('upload_photos', csrf_exempt(views.upload_photos), name="upload_photos"),
Just for testing, I will remove this, I use postman to have a test

2022-03-25 22:24 UTC, desolee commented on flinder/templates/flinder/upload_photos.html
> +            </form>
OK, as long as it post the img to the backend, then that's fine

2022-03-26 01:00 UTC, space928 approved these changes

2022-03-26 01:00 UTC, merged